In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from sklearn import model_selection
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from nltk.corpus import stopwords 
from sklearn.feature_extraction.text import HashingVectorizer
from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer 

In [2]:
train=pd.read_csv(r"C:\Users\jinci\Desktop\nlp-getting-started\train.csv")
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [3]:
test=pd.read_csv(r"C:\Users\jinci\Desktop\nlp-getting-started\test.csv")
test.tail()

id keyword location  \
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...

In [4]:
train_text=train.text
train_target=train.target
test_text=test.text

In [96]:
vectorizer=CountVectorizer()
vectorizer.fit(train_text)
X_train=vectorizer.transform(train_text)
X_test=vectorizer.transform(test_text)
X_train

<7613x21637 sparse matrix of type '<class 'numpy.int64'>'
	with 111497 stored elements in Compressed Sparse Row format>

In [95]:
stopwords=stopwords.words('english')
vectorizer1=CountVectorizer(strip_accents='ascii',stop_words=stopwords,ngram_range=(1,5),max_df=0.95)
vectorizer1.fit(train_text)
X_train1=vectorizer1.transform(train_text)
X_test1=vectorizer1.transform(test_text)
X_train1

<7613x232480 sparse matrix of type '<class 'numpy.int64'>'
	with 344172 stored elements in Compressed Sparse Row format>

In [97]:
vectorizer2=TfidfVectorizer()
vectorizer2.fit(train_text)
X_train2=vectorizer2.transform(train_text)
X_test2=vectorizer2.transform(test_text)
X_train2

<7613x21637 sparse matrix of type '<class 'numpy.float64'>'
	with 111497 stored elements in Compressed Sparse Row format>

In [98]:
max_n3=15
vectorizer3=TfidfVectorizer(strip_accents='unicode',ngram_range=(1,max_n3),)
vectorizer3.fit(train_text)
X_train3=vectorizer3.transform(train_text)
X_test3=vectorizer3.transform(test_text)
X_train3

<7613x773102 sparse matrix of type '<class 'numpy.float64'>'
	with 1010757 stored elements in Compressed Sparse Row format>

In [90]:
class LemmaTokenizer:
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, doc):
        return [self.wnl.lemmatize(t) for t in word_tokenize(doc)]

vectorizer4=CountVectorizer(tokenizer=LemmaTokenizer())
vectorizer4.fit(train_text)
X_train4=vectorizer4.transform(train_text)
X_test4=vectorizer4.transform(test_text)
X_train4

<7613x21996 sparse matrix of type '<class 'numpy.int64'>'
	with 128167 stored elements in Compressed Sparse Row format>

In [118]:
print(X_train[0].todense())
print(X_train1[0].todense())
print(X_train2[0].todense())

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0. 0. 0. ... 0. 0. 0.]]


In [24]:
# Establecemos a la regresion logistica como clasificador
cls=LogisticRegression()


In [100]:
# Establecemos un score, usamos f1 que es el utilizado en competencia
score=model_selection.cross_val_score(cls,X_train,train.target,cv=10,scoring='f1')
score

C:\Users\jinci\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.62956522, 0.56218058, 0.51779935, 0.5152    , 0.5800317 ,
       0.6048    , 0.58983051, 0.52532833, 0.70788253, 0.72941176])

In [99]:
score1=model_selection.cross_val_score(cls,X_train1,train.target,cv=10,scoring='f1')
score1


C:\Users\jinci\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.58113208, 0.47524752, 0.46704331, 0.53214286, 0.49446494,
       0.57692308, 0.55893536, 0.42173913, 0.65964912, 0.72758037])

In [103]:
score2=model_selection.cross_val_score(cls,X_train2,train.target,cv=10,scoring='f1')
score2

C:\Users\jinci\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.64084507, 0.62239089, 0.56624319, 0.5915493 , 0.61217391,
       0.62650602, 0.61202186, 0.57685009, 0.69505963, 0.74598071])

In [105]:
score3=model_selection.cross_val_score(cls,X_train3,train.target,cv=10,scoring='f1')
score3

C:\Users\jinci\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.2915601 , 0.24415584, 0.28426396, 0.25      , 0.21705426,
       0.22942643, 0.19672131, 0.29648241, 0.31862745, 0.46052632])

In [106]:
score4=model_selection.cross_val_score(cls,X_train4,train.target,cv=10,scoring='f1')
score4

C:\Users\jinci\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.64248705, 0.53767123, 0.53269537, 0.53125   , 0.609375  ,
       0.57463884, 0.6013289 , 0.53141831, 0.72977099, 0.73669065])

In [109]:
score4>score2

array([ True, False, False, False, False, False, False, False,  True,
       False])

In [115]:
#Ajusto para el 4to modelo
cls.fit(X_train4,train.target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
sample_submission=pd.read_csv(r"C:\Users\jinci\Desktop\nlp-getting-started\sample_submission.csv")

In [116]:
# De nuevo, trabajo con el 4to modelo
sample_submission['target']=cls.predict(X_test4)


In [117]:
#Creo el csv con el cuarto modelo
sample_submission.to_csv('sub4.csv',index=False)